config/routes.rb
Rails.application.routes.draw do

  resources :tag do
    collection do
      get :tag_name
    end
  end
  namespace :admin do
    resources :articles , :id => /.*/ 
    root 'articles#index'
  end
  resources :article , :id => /.*/ do
    collection do
      # get '/:id' => 'article#show', :as => :category, :article => { :id => /[\w+\.]+/ }
      get :search
    end
  end
  resources :users  
  get '/login', to: 'users#login'
  get 'check' => 'article#checkUser'
  root 'article#index'

  mount ApplicationApi => '/api'
  mount GrapeSwaggerRails::Engine => '/apidoc'
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user ,optional: true
  has_many :tag_article_relationships,dependent: :destroy
  has_many :tags, through: :tag_article_relationships,dependent: :destroy
  extend FriendlyId
  friendly_id :title

  second_level_cache expires_in: 1.week

  class << self

  	def article_to_md
  		all = Article.all
  		all.each do |a|
  			file = File.open("/Users/liuxin/Me/blog/other/" + a.title+'.md','ab+')

  			print a.title
  			tags = ''
  			a.tags.each do |t|
  				tags+=t.tag_name.to_s+','
  			end
  			tags =  tags[0,tags.size-1]
  			str = "```\r\ntags:" + tags.to_s + "\r\n```\r\n"
  			body = str + a.content
  			file.syswrite(body)
  		end
  	end


  end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseController
  before_action :set_article, only: [:show, :edit, :destroy,:update]
  before_action :set_article_is_is_original, only: [:create, :update]
  def index
    @articles = Article.all.order(id: :desc).page(params[:page]).per(10)
  end

  def show
    @page_title       = @article.title
    @page_description = @article.content.split('<!--more-->')[0].gsub('##','####').gsub(/^#.*?\s+/,'#### ')
    @page_keywords = @article.tags
  end

  def update
    ord_tags = @article.tags.ids
    @article.update(
       title:raticles_params[:title],
       content:raticles_params[:content],
       source_title:raticles_params[:source_title],
       source_url:raticles_params[:source_url],
       is_original:@is_original
       )
    # 删除当前关联
    @article.tags.delete_all
    raticles_params[:tags].split(',').each do |t|
      tag = Tag.find_by(tag_name: t)
      unless tag.present? && TagArticleRelationship.find_by(article_id: @article.id,tag_id:tag.id)
        @article.tags << Tag.find_or_create_by(tag_name: t)
      end
    end

    ord_tags.each do |tag|
      articles = Tag.find_by_id(tag).articles.count
      if articles == 0
        Tag.find_by_id(tag).delete
      end
    end
    redirect_to article_url(params[:id]),notice: "文章更新成功！"
  end

  def edit
    @tags = ''
    if @article.tags.present?
      @article.tags.each do|t|
        @tags+=t.tag_name+','
      end
    end

  end

  def destroy
    @article.destroy
    redirect_to admin_articles_url,notice: "文章删除成功！"
  end

  def create
    a = {
      "title" => raticles_params[:title],
      "content" => raticles_params[:content],
      "source_title"=> raticles_params[:source_title],
      "source_url"=> raticles_params[:source_url],
      "is_original"=> @is_original
    }
    @article = Article.new(a)
    begin
      @article.transaction do
        @article.user_id = current_user.id
        @article.read = 1
        ActiveRecord::Base.transaction do
          if @article.save
            raticles_params[:tags].split(',').each do |t|
              tag = Tag.find_by(tag_name: t)
              p tag
              if tag.present? && TagArticleRelationship.find_by(article_id: @article.id,tag_id:tag.id)
                p '已存在'
              else
                @article.tags << Tag.find_or_create_by(tag_name: t)
              end
            end
            redirect_to admin_article_url(@article.id) ,notice: "文章创建成功！"
          else
            redirect_to new_admin_article_path ,alert: "发表失败!" << @articles.errors.full_messages.to_s
          end
        end
      end
    rescue Exception => e
      redirect_to new_admin_article_path ,alert: "发表失败!" + e.message
    end
  end

  def new
    @article = Article.new
  end

  private
  def raticles_params
    params.require(:article).permit(:title,:content,:tags,:source_title, :source_url)
  end

  def set_article
    @article = Article.friendly.includes(:tags).find(params[:id])
  end

  def set_article_is_is_original
    @is_original = true
    if raticles_params[:source_title]!="liuxin's blog" || raticles_params[:source_url].present?
      @is_original = false
    end
  end
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
  include SessionsHelper
  before_action :set_article, only: [:show]
  before_action :set_tags, only: [:index,:show,:search]

  def index
    @page_keywords = ''
    Tag.all.each do |c|
      @page_keywords += "#{c.tag_name},"
    end
    fresh_when  @articles = Article.all.includes(:tags).order(id: :desc).page(params[:page]).per(5)
  end

  def show
    @page_title       = @article.title
    @page_description = @article.content.split('<!--more-->')[0].gsub('##','####').gsub(/^#.*?\s+/,'#### ')
    @page_keywords = ''
    @article.tags.each do |c|
      @page_keywords += "#{c.tag_name},"
    end
    fresh_when @article.update!(read: @article.read+=1)
  end

  def checkUser
    if params[:user].present?
      Rails.logger.info "login user ==== #{params[:user]}"
      user = User.where(address: params[:user].to_s)
      Rails.logger.info "user ? ==#{user.count}"
      if user.count > 0
        if current_user.present?
          if current_user.address.to_s == params[:user].to_s
            render json:{'message'=>'Logged in!',"result" => 1}
          end
        else
          log_in user.first
          render json:{'message'=>'Login successful!',"result" => 1}
        end
      else
        respond_to do |format|
          log_out
          format.html {redirect_to article_index_url}
          format.js {}
          format.json {
            render json: {'message'=>'error',result:0}
          }
        end
      end
    end
  end

  def search
    validate_search_key
    if @query_string.present?
      search_result = Article.ransack(@search_criteria).result(:distinct => true)
      @articles = search_result.page(params[:page]).per(10)
    end
  end

  protected

    def validate_search_key
      @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
      @search_criteria = search_criteria(@query_string)
    end

    def search_criteria(query_string)
      { title_or_content_cont: query_string }
    end

    def set_article
      @article = Article.friendly.includes(:tags).find(params[:id])
    end

    def set_tags
      @tags = Tag.all.includes(:articles).includes(:tag_article_relationships).order(id: :desc)
      @tags_list = Tag.find_by_sql('SELECT T.ID,T.tag_name, f.COUNT  FROM ( SELECT tags.ID, COUNT ( tag_name ) FROM tags JOIN tag_article_relationships ON tags.ID = tag_article_relationships.tag_id GROUP BY tags.ID ) f JOIN tags T ON T.ID = f.ID')
    end
end

app/helpers/admin/article_helper.rb
module Admin::ArticleHelper
end

app/helpers/article_helper.rb
module ArticleHelper
  def render_highlight_content(group,query_string)
    excerpt_cont = excerpt(group.title, query_string, radius: 500)
    highlight(excerpt_cont, query_string)
  end
end

app/views/admin/articles/_form.html.erb
<div class="card">
 <div class="card-header">
  <h2>新建文章</h2>
</div>
<div class="card-body" >
  <%= simple_form_for([:admin, @article]) do |f| %>
  <div class="title">

    <%= f.input :title ,label: '标题',input_html: { class: 'form-control'}%>
  </div>
  <div class="row justify-content-between">
    <div class="col-md-4">
      <%= f.input :source_title ,label: "来源标题", input_html: { class: 'form-control '}%>
    </div>
    <div class="col-md-6 ml-auto">
      <%= f.input :source_url ,label: "来源url", input_html: { class: 'form-control '}%>
    </div>
  </div>
  <%= f.label "正文"%>
  <%= f.text_area :content,rows:30,class: 'form-control'%>
  <span class="hint">支持markdown语法</span>

  <div class="input string optional article_tags">
    <label class="string optional" for="article_tags">标签</label>
    <input data-role='tagsinput' class="string optional form-control" placeholder="多个标签用逗号隔开" type="text" value="<%=@tags%>" name="article[tags]" id="article_tags" >
  </div>
  <div style="margin-top: 30px;" align="center">
    <%= f.submit "保存",class:' btn btn-primary btn-lg ' ,style:'width:100%;'%>
  </div>
  <% end%>
</div>
</div>

app/views/admin/articles/edit.html.erb
<div class="row">
  <div class="container">
    <h2>修改文章</h2>
    <%= render 'form'%>
  </div>
</div>

app/views/admin/articles/index.html.erb
<div class="card">
  <table class="table table-hover">
    <thead class="thead-light">
      <tr>
        <th>id</th>
        <th>题目</th>
        <th>创建时间</th>
        <th>标签</th>
        <th>浏览量</th>
        <th>查看详情</th>
        <th>编辑</th>
        <th>删除</th>
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |a| %>
      <tr>
        <td><%= a.id %></td>
        <td><%= a.title%></td>
        <td><%= a.created_at.strftime("%Y-%m-%d %H:%M") %></td>
        <td>
          <%a.tags.each do |t| %>
          <span class="badge badge-secondary"><%=t.tag_name%></span>
          <%end%>
        </td>
        <td><%= a.read%></td>
        <td>
          <%= link_to 'show',admin_article_path(a), class:'btn btn-success btn-sm'%>
        </td>
        <td><%= link_to '编辑',edit_admin_article_url(a.id), class:'btn btn-info btn-sm'%></td>
        <td><%= link_to 'destroy',{controller: 'articles',action:'destroy',id:a.id}, method: :delete,data: { confirm: '你确定要删除该篇文章?' }, class:'btn btn-danger btn-sm'%></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div  class="text-center">
  <%= paginate @articles %>
</div>

app/views/admin/articles/new.html.erb
<%= render 'form'%>

app/views/admin/articles/show.html.erb
<div class="row">
<%= render 'shared/article' %>
</div>