config/routes.rb
Rails.application.routes.draw do

  resources :tag do
    collection do
      get :tag_name
    end
  end
  namespace :admin do
    resources :articles , :id => /.*/ 
    root 'articles#index'
  end
  resources :article , :id => /.*/ do
    collection do
      # get '/:id' => 'article#show', :as => :category, :article => { :id => /[\w+\.]+/ }
      get :search
    end
  end
  resources :users  
  get '/login', to: 'users#login'
  get 'check' => 'article#checkUser'
  root 'article#index'

  mount ApplicationApi => '/api'
  mount GrapeSwaggerRails::Engine => '/apidoc'
end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>管理中心</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="adminMainContent">
    <div  class="container " >
      <ul class="nav justify-content-center">
        <li class="nav-item">
          <a class="nav-link" href="<%= root_url%>">
            liuxin's blog
          </a>
        </li>
        <li class="nav-item">
          <%= link_to '新建文章',new_admin_article_path,class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to '文章列表',admin_articles_path,class:"nav-link"%>
        </li>
      </ul>
      <%=notice_message%>
        <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </div>
</body>
</html>