config/routes.rb
Rails.application.routes.draw do

  resources :tag do
    collection do
      get :tag_name
    end
  end
  namespace :admin do
    resources :articles , :id => /.*/ 
    root 'articles#index'
  end
  resources :article , :id => /.*/ do
    collection do
      # get '/:id' => 'article#show', :as => :category, :article => { :id => /[\w+\.]+/ }
      get :search
    end
  end
  resources :users  
  get '/login', to: 'users#login'
  get 'check' => 'article#checkUser'
  root 'article#index'

  mount ApplicationApi => '/api'
  mount GrapeSwaggerRails::Engine => '/apidoc'
end

app/models/user.rb
class User < ApplicationRecord
	has_many :articles
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def login
  	@user = User.new;
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper

  def login
  
  end

  def create
    if params[:user].present?
      Rails.logger.info "login user ==== #{params[:user]}"
      user = User.where(address: params[:user][:address].to_s)
      Rails.logger.info "user ? ==#{user.count}"
      if user.count > 0
        if current_user.present?
          if current_user.address.to_s == params[:user].to_s
            respond_to do |format|
              format.html {redirect_to admin_articles_url}
            end
          end
        else
          log_in user.first
          respond_to do |format|
            format.html {redirect_to admin_articles_url}
          end
        end 
      else
        respond_to do |format|
          format.html {redirect_to article_index_url} 
        end
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/login.html.erb
<div class="col-lg-4"></div>
<div class="col-lg-4" style="text-align: center!important;">

  <%= form_for(:user, url: users_path) do |f| %>

    <%= f.label :Login %>
    <%= f.text_field :address, class: 'form-control' , type: "password" %>	
    <hr>
    <%= f.submit "Log in", class: "btn btn-lg btn-primary btn-bloc" ,type: "submit" %>
  <% end %>

</div>
<div class="col-lg-4"></div>

app/views/users/new.html.erb
<div class="col-md-6">
  <%= form_for(:login, url: new_user_path) do |f| %>

    <%= f.label :address %>
    <%= f.email_field :address, class: 'form-control' %>

    <%= f.submit "Log in", class: "btn btn-primary" %>
  <% end %>
</div>