config/routes.rb
Rails.application.routes.draw do

  resources :tag do
    collection do
      get :tag_name
    end
  end
  namespace :admin do
    resources :articles , :id => /.*/ 
    root 'articles#index'
  end
  resources :article , :id => /.*/ do
    collection do
      # get '/:id' => 'article#show', :as => :category, :article => { :id => /[\w+\.]+/ }
      get :search
    end
  end
  resources :users  
  get '/login', to: 'users#login'
  get 'check' => 'article#checkUser'
  root 'article#index'

  mount ApplicationApi => '/api'
  mount GrapeSwaggerRails::Engine => '/apidoc'
end

app/views/shared/_appreciates_code.html.erb
<div class="card" style="margin-top: 15px;text-align: center;">
  <div class="card-body" style="background-color: #FFF;border-radius: 10px;">
    <button class="btn btn-primary btn-block" type="button" data-toggle="modal" data-target="#appreciates">🎉🎉 赞赏支持 🎉🎉</button>
  </div>
</div>

app/views/shared/_article.html.erb
<div class="card">
  <div class="card-header" align="center" >

    <h4><%= @article.title%></h4>
    <div style="color: #8590A6;font-size: 13px;">
      <i class="far fa-calendar-alt"></i>
      <span><%=@article.created_at.strftime("%Y-%m-%d %H:%M")%></span>
      <span><%tags = @article.tags %></span>
      <span>
        <i class="fas fa-eye"></i>
        <%=@article.read%>
      </span>
      来源:
      <span class="badge badge-<%= @article.is_original ? 'success':'danger'%>" >
        <%if @article.is_original %>
        <%= @article.source_title%>
        <%else%>
        <a href="<%= @article.source_url%>" style="color: #fff;" target="_blank" >
          <%= @article.source_title%>
        </a>
        <%end%>
      </span>
      <%unless !logged_in?%>
      &nbsp | <%= link_to '编辑',edit_admin_article_url(@article.id)%>
      <%= link_to '删除',{controller: 'admin/articles',action:'destroy',id:@article.id}, method: :delete,data: { confirm: "你确定要删除该篇文章?\n #{@article.title}"}%>
      <%end%>
      <br>
      <%if tags.size > 0%>
      <%tags.each do |tag| %>
      <i class="fas fa-tag">
        <%= link_to tag.tag_name ,tag_index_path(:tag_name => tag.tag_name) ,class: "badge badge-secondary"%>
      </i>
      <%end%>
      <%end%>
    </div>
  </div>
  <div class="card-body">

    <div id="blog-content" data-content="<%= @article.content %>">
    </div>
    <hr>

    <% if @article.is_original%>
    <div class="original">
      <p align="center">原创文章欢迎转载,转载请注明出处</p>
      <p><strong>标题：</strong><%= @article.title%> | <strong>作者：</strong><%= @article.user.nickname%></p>
      <p><strong>地址：</strong><a href="<%=URI.decode(article_url(@article.title))%>"><%=URI.decode(article_url(@article.title))%></a></p>
      <%else%>
      <div class="statement">
        <!-- <div class="card text-white bg-warning"> -->
          <p>转载文章</p>
          <p><strong>标题：</strong><a href="<%= @article.source_url%>"  target="_blank" ><%= @article.source_title%></a></p>
          <p><strong>地址：</strong><%= @article.source_url%></p>
          <p ><kbd>我无意冒犯您的版权,如果侵犯到您的权益.请联系我删除.</kbd></p>
          <%end%>
        </div>
      </div>
    </div>

app/views/shared/_article_list.html.erb
<%@articles.each do |a|%>
<div class="card article-list" >
  <div class="card-body">
    <h4  align="left">
      <%= link_to a.title,article_path(a) ,class:'post-title' ,style: "color: #333"%>
    </h4>
    <div class="content" data-content='<%=a.content.split('<!--more-->')[0].gsub('##','####').gsub(/^#.*?\s+/,'#### ')%>' id="blog_<%=a.id%>">
    </div>
    <div class="row justify-content-between">
      <div class="col-auto mr-auto"  >
        <%if a.tags.size > 0%>
        <%a.tags.each do |tag| %>
        <span class="align-items-start" style="font-size: 0.9rem;" >
          <i class="fas fa-tag">
            <%= link_to tag.tag_name ,tag_index_path(:tag_name => tag.tag_name) ,class: "badge badge-secondary"%>
          </i>
        </span>
        <%end%>
        <%end%>
      </div>
      <div class="col-auto" >
        <span style="color: #777;font-size: 0.9rem" align="center">
          <i class="far fa-calendar-alt"></i>
          <%=a.created_at.strftime("%Y-%m-%d %H:%M")%>
          <i class="fas fa-eye"></i>
          <%=a.read%>
        </span>
        <%= link_to '阅读更多',article_path(a) ,class:'btn btn-outline-success btn-sm'%>
      </div>
    </div>
  </div>
</div>
<%end%>
<div class="paginate-card card" >
  <%= paginate @articles if !@articles.nil? %>
</div>

app/views/shared/_contact.html.erb
<div class="card">
  <div class="card-body" >
    <!-- 自己加的页脚微信展示开始 -->
    <% cache  do %>
    <div class="row">
      <div class="col-md-4" align="center">
        <a id="weixin" href="javascript:void(0)">
          <i class="fab fa-weixin" style="font-size: 30px;color: #33DB55"></i>
          <img src="<%= image_url('wechat_code.jpg') %>" />
        </a>
      </div>
      <div class="col-md-4" align="center">
        <a id="weixin" href="https://weibo.com/5329788710/profile?topnav=1&wvr=6" target="_blank">
          <i class="fab fa-weibo" style="font-size: 30px;color: #d80022"></i>
        </a>
      </div>
      <div class="col-md-4" align="center">
        <a  id="weixin" href="https://github.com/myvary" target="_blank" >
          <i class="fab fa-github" style="font-size: 30px;color: #444;"></i>
        </a>
      </div>
    </div>
    <% end %>
    <!-- 自己加的页脚微信展示结束 -->
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer hidden-mobile" id ='footer'>
  <span>© <%= Date.today.year %> liuxin's blog</span>
</footer>

app/views/shared/_header.html.erb
<div style="margin-bottom:58px;">
 <nav class="navbar navbar-expand-lg  fixed-top navbar-light bg-light">
   <div class="container">
    <a class="navbar-brand" href="<%= root_url%>">liuxin's blog</a>
    <button class="navbar-toggler btn btn-sm" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      </ul>
      <%= form_tag search_article_index_path , :method => :get ,class: "form-inline my-2 my-lg-0" do%>
      <div class="input-group" role="group" id="search-id">
        <input type="text" class="form-control" name="q" value="<%= params[:q] %>" placeholder="Search">
        <div class="input-group-append">
          <button class="btn btn-primary" type="submit">
            <i class="fa fa-search"></i>
          </button>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</nav>
</div>

app/views/shared/_search.html.erb
<div class="card">
  <div class="card-body" >
    <%= form_tag search_article_index_path , :method => :get do %>
    <div class="input-group" role="group" id="search-id">
      <input type="text" class="form-control" name="q" value="<%= params[:q] %>" placeholder="Search">
      <div class="input-group-append">
        <button class="btn btn-primary" type="submit">
          <i class="fa fa-search"></i>
        </button>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/shared/_tags.html.erb
<div class="card">
  <div class="card-header" align="center"><i class="fas fa-tags"></i> 标签</div>
  <div class="card-body">
    
    <% @tags_list.each do |t|%>
    <a class='badge badge-secondary' href="<%=tag_index_path(:tag_name => t.tag_name)%>"><%=t.tag_name%> <span><%=t.count.to_s%></span></a>
  
    
    <%end%>
  </div>
</div>